from System import Array_1
from AudioPrecision.API import IApplication

class SampleData:
    SampleRate : int
    Samples : Array_1[float]
    @property
    def HasSamples(self) -> bool: ...


class WaveFileInfo:
    @property
    def BitsPerSample(self) -> int: ...
    @property
    def DurationInSamples(self) -> int: ...
    @property
    def IsDigital(self) -> bool: ...
    @property
    def NumChs(self) -> int: ...
    @property
    def SampleRate(self) -> int: ...
    def CreateReader(self) -> WaveReader: ...


class WaveReader:
    def __init__(self, apx: IApplication) -> None: ...
    @staticmethod
    def GetFileInfo(fileName: str) -> WaveFileInfo: ...
    def ReadSamples(self, numSamples: int, timeoutInMs: int) -> SampleData: ...
    def StartMeasurementRecorder(self, signalPath: str, measurement: str, numChsToRead: int, openDelay: int = ...) -> None: ...


class WavFileInfo:
    @property
    def CarrierBitsPerSample(self) -> int: ...
    @property
    def IsEncoded(self) -> bool: ...
    def GetCarrierSampleRate(self) -> float: ...
    def GetNumCarrierChannels(self) -> int: ...
    def GetNumSamplesPerBurst(self) -> int: ...

